spring:
  application:
    name: eureka-service-provider
server:
  port: 8080
eureka:
  client:
    service-url:
#      default-zone: http://localhost:8761/eureka/
      default-zone: http://localhost:8761/eureka/,http://localhost2:8762/eureka/


